repos:
- repo: local
  hooks:
  - id: linter
    name: linter
    entry: hatch run lint
    language: system
    types: [python]
  - id: format
    name: format
    entry: hatch run format --diff
    language: system
    types: [python]
