name: Broken site support
description: Report broken or misfunctioning site
labels: [triage, extractor-bug]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |
        Carefully read and work through this check list in order to prevent the most common mistakes and misuse of yt-dlp:
        - First off, make sure you are using the latest version of yt-dlp. Run `yt-dlp --version` and ensure your version is %(version)s. If it's not, see [this](https://github.com/yt-dlp/yt-dlp#update) on how to update. Issues with outdated version will be REJECTED.
        - Make sure that all provided video/audio/playlist URLs (if any) are alive and playable in a browser.
        - Make sure that all URLs and arguments with special characters are properly quoted or escaped.
        - Read "[opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)" section in [CONTRIBUTING.md](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md) 
        - Search the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues) for similar issues. DO NOT post duplicates.
        - Read "[Are you willing to share account details if needed?](https://github.com/Ashish0804/ytdlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed)" section in [CONTRIBUTING.md](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md)
      options:
        - label: I'm reporting a broken site
          required: true
        - label: I've verified that I'm running yt-dlp version **%(version)s**
          required: true
        - label: I've checked that all provided URLs are alive and playable in a browser
          required: true
        - label: I've checked that all URLs and arguments with special characters are properly quoted or escaped
          required: true
        - label: I've searched the bugtracker for similar issues including closed ones
          required: true
        - label: I've read the opening an issue section in CONTRIBUTING.md
          required: true
        - label: I've given an appropriate title to the issue
          required: true
        - label: I've read the Are you willing to share account details if needed? section in CONTRIBUTING.md
          required: true
        - label: I'm willing to share account credentials if required
  - type: input
    id: region
    attributes:
      label: Region
      description: "Enter the region the site is accessible from"
      placeholder: "India"
  - type: textarea
    id: log
    attributes:
      label: Verbose log
      description: |
        Provide the complete verbose output of yt-dlp that clearly demonstrates the problem.
        Add the `-v` flag to your command line you run yt-dlp with (`yt-dlp -v <your command line>`), copy the WHOLE output and insert it below. It should look similar to this:
         [debug] System config: []
         [debug] User config: []
         [debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKc']
         [debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
         [debug] yt-dlp version %(version)s
         [debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
         [debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
         [debug] Proxy map: {}
         <more lines>
      placeholder: PASTE VERBOSE LOG HERE
      render: shell
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Provide an explanation of your issue in an arbitrary form. Provide any additional information, suggested solution and as much context and examples as possible.
        If work on your issue requires account credentials please provide them or explain how one can obtain them.
      placeholder: WRITE DESCRIPTION HERE
    validations:
      required: true