name: Site feature request
description: Request a new functionality for a site
labels: [triage, site-enhancement]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |
        Carefully read and work through this check list in order to prevent the most common mistakes and misuse of yt-dlp:
        - First off, make sure you are using the latest version of yt-dlp. Run `yt-dlp --version` and ensure your version is %(version)s. If it's not, see [this](https://github.com/yt-dlp/yt-dlp#update) on how to update. Issues with outdated version will be REJECTED.
        - Read "[opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)" section in [CONTRIBUTING.md](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md) 
        - Search the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues) for similar issues. DO NOT post duplicates.
        - Read "[Are you willing to share account details if needed?](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed)" section in [CONTRIBUTING.md](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md)
      options:
        - label: I'm reporting a site feature request
          required: true
        - label: I've verified that I'm running yt-dlp version **%(version)s**
          required: true
        - label: I've searched the bugtracker for similar issues including closed ones
          required: true
        - label: I've read the opening an issue section in CONTRIBUTING.md
          required: true
        - label: I've given an appropriate title to the issue
          required: true
        - label: I've read the Are you willing to share account details if needed? section in CONTRIBUTING.md
          required: true
        - label: I'm willing to share account credentials if required
  - type: input
    id: region
    attributes:
      label: Region
      description: "Enter the region the site is accessible from"
      placeholder: "India"
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Provide an explanation of your site feature request in an arbitrary form. Please make sure the description is worded well enough to be understood, see [is-the-description-of-the-issue-itself-sufficient](https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient).
        Provide any additional information, suggested solution and as much context and examples as possible.
      placeholder: WRITE DESCRIPTION HERE
    validations:
      required: true