name: Ask question
description: Ask yt-dlp related question
labels: [question]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |
        Carefully read and work through this check list in order to prevent the most common mistakes and misuse of yt-dlp:
        - Look through the [README](https://github.com/yt-dlp/yt-dlp)
        - Read "[opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)" section in [CONTRIBUTING.md](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md) 
        - Search the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues) for similar questions
      options:
        - label: I'm asking a question and not reporting a bug/feature request
          required: true
        - label: I've looked through the README
          required: true
        - label: I've read the opening an issue section in CONTRIBUTING.md
          required: true
        - label: I've searched the bugtracker for similar questions including closed ones
          required: true
        - label: I've given an appropriate title to the issue
          required: true
  - type: textarea
    id: question
    attributes:
      label: Question
      description: "Ask your question in an arbitrary form. Please make sure it's worded well enough to be understood, see https://github.com/yt-dlp/yt-dlp."
      placeholder: WRITE QUESTION HERE
    validations:
      required: true