name: Site support request
description: Request support for a new site
labels: [triage, site-request]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |
        Carefully read and work through this check list in order to prevent the most common mistakes and misuse of yt-dlp:
        - First off, make sure you are using the latest version of yt-dlp. Run `yt-dlp --version` and ensure your version is 2021.10.10. If it's not, see [this](https://github.com/yt-dlp/yt-dlp#update) on how to update. Issues with outdated version will be REJECTED.
        - Make sure that all provided video/audio/playlist URLs (if any) are alive and playable in a browser.
        - Make sure that site you are requesting is not dedicated to copyright infringement. yt-dlp does not support such sites. In order for site support request to be accepted all provided example URLs should not violate any copyrights.
        - Read "[opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)" section in [CONTRIBUTING.md](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md) 
        - Search the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues) for similar issues. DO NOT post duplicates.
        - Read "[Are you willing to share account details if needed?](https://github.com/Ashish0804/ytdlp-issues-dev/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed)" section in [CONTRIBUTING.md](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md)
      options:
        - label: I'm reporting a new site support request
          required: true
        - label: I've verified that I'm running yt-dlp version **2021.10.10**
          required: true
        - label: I've checked that all provided URLs are alive and playable in a browser
          required: true
        - label: I've checked that none of provided URLs violate any copyrights
          required: true
        - label: The provided URLs do not contain any DRM to the best of my knowledge
          required: true
        - label: I've searched the bugtracker for similar issues including closed ones
          required: true
        - label: I've read the opening an issue section in CONTRIBUTING.md
          required: true
        - label: I've given an appropriate title to the issue
          required: true
        - label: I've read the Are you willing to share account details if needed? section in CONTRIBUTING.md
          required: true
        - label: I'm willing to share account credentials if required
  - type: input
    id: region
    attributes:
      label: Region
      description: "Enter the region the site is accessible from"
      placeholder: "India"
  - type: textarea
    id: example-urls
    attributes:
      label: Example URLs
      description: |
        Provide all kinds of example URLs, support for which should be included. Replace following example URLs by yours.
      value: |
        - Single video: https://www.youtube.com/watch?v=BaW_jenozKc
        - Single video: https://youtu.be/BaW_jenozKc
        - Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Provide any additional information.
        If work on your issue requires account credentials please provide them or explain how one can obtain them.
      placeholder: WRITE DESCRIPTION HERE
    validations:
      required: true