name: Build

on:
  push:
    branches:
      - release

jobs:
  build_unix:

    runs-on: ubuntu-latest

    outputs:
      ytdlc_version: ${{ steps.bump_version.outputs.ytdlc_version }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      sha2_unix: ${{ steps.sha2_file.outputs.sha2_unix }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: '3.8'
    - name: Install packages
      run: sudo apt-get -y install zip pandoc man
    - name: Bump version
      id: bump_version
      run: python devscripts/update-version.py
    - name: Print version
      run: echo "${{ steps.bump_version.outputs.ytdlc_version }}"
    - name: Run Make
      run: make
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.bump_version.outputs.ytdlc_version }}
        release_name: yt-dlp ${{ steps.bump_version.outputs.ytdlc_version }}
        body: |
          Changelog:
          PLACEHOLDER
        draft: false
        prerelease: false
    - name: Upload youtube-dlc Unix binary
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./youtube-dlc
        asset_name: youtube-dlc
        asset_content_type: application/octet-stream
    - name: Get SHA2-256SUMS for youtube-dlc
      id: sha2_file
      run: echo "::set-output name=sha2_unix::$(sha256sum youtube-dlc)"

  build_windows:

    runs-on: windows-latest

    outputs:
      sha2_windows: ${{ steps.sha2_file_win.outputs.sha2_windows }}

    needs: build_unix

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: '3.8'
    - name: Install Requirements
      run: pip install pyinstaller mutagen pycryptodome
    - name: Bump version
      id: bump_version
      run: python devscripts/update-version.py
    - name: Print version
      run: echo "${{ steps.bump_version.outputs.ytdlc_version }}"
    - name: Run PyInstaller Script
      run: python pyinst.py 64
    - name: Upload youtube-dlc.exe Windows binary
      id: upload-release-windows
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.build_unix.outputs.upload_url }}
        asset_path: ./dist/youtube-dlc.exe
        asset_name: youtube-dlc.exe
        asset_content_type: application/vnd.microsoft.portable-executable
    - name: Get SHA2-256SUMS for youtube-dlc.exe
      id: sha2_file_win
      run: echo "::set-output name=sha2_windows::$(certUtil -hashfile dist\youtube-dlc.exe SHA256 | findstr -v :)"

  build_windows32:

    runs-on: windows-latest

    outputs:
      sha2_windows32: ${{ steps.sha2_file_win32.outputs.sha2_windows32 }}

    needs: [build_unix, build_windows]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.4.4 32-Bit
      uses: actions/setup-python@v2
      with:
          python-version: '3.4.4'
          architecture: 'x86'
    - name: Install VS libs
      run: choco install vcexpress2010
    - name: Install Requirements for 32 Bit
      run: pip install pyinstaller==3.5 mutagen pycryptodome
    - name: Bump version
      id: bump_version
      run: python devscripts/update-version.py
    - name: Print version
      run: echo "${{ steps.bump_version.outputs.ytdlc_version }}"
    - name: Run PyInstaller Script for 32 Bit
      run: python pyinst.py 32
    - name: Upload Executable youtube-dlc_x86.exe
      id: upload-release-windows32
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.build_unix.outputs.upload_url }}
        asset_path: ./dist/youtube-dlc_x86.exe
        asset_name: youtube-dlc_x86.exe
        asset_content_type: application/vnd.microsoft.portable-executable
    - name: Get SHA2-256SUMS for youtube-dlc_x86.exe
      id: sha2_file_win32
      run: echo "::set-output name=sha2_windows32::$(certUtil -hashfile dist\youtube-dlc_x86.exe SHA256 | findstr -v :)"
    - name: Make SHA2-256SUMS file
      env:
        SHA2_WINDOWS: ${{ needs.build_windows.outputs.sha2_windows }}
        SHA2_WINDOWS32: ${{ steps.sha2_file_win32.outputs.sha2_windows32 }}
        SHA2_UNIX: ${{ needs.build_unix.outputs.sha2_unix }}
        YTDLC_VERSION: ${{ needs.build_unix.outputs.ytdlc_version }}
      run: |
        echo "version:${env:YTDLC_VERSION}" >> SHA2-256SUMS
        echo "youtube-dlc.exe:${env:SHA2_WINDOWS}" >> SHA2-256SUMS
        echo "youtube-dlc_x86.exe:${env:SHA2_WINDOWS32}" >> SHA2-256SUMS
        echo "youtube-dlc:${env:SHA2_UNIX}" >> SHA2-256SUMS

    - name: Upload 256SUMS file
      id: upload-sums
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.build_unix.outputs.upload_url }}
        asset_path: ./SHA2-256SUMS
        asset_name: SHA2-256SUMS
        asset_content_type: text/plain

#  update_version_badge:
#    runs-on: ubuntu-latest
#    needs: build_unix
#    steps:
#    - name: Create Version Badge
#      uses: schneegans/dynamic-badges-action@v1.0.0
#      with:
#        auth: ${{ secrets.GIST_TOKEN }}
#        gistID: c69cb23c3c5b3316248e52022790aa57
#        filename: version.json
#        label: Version
#        message: ${{ needs.build_unix.outputs.ytdlc_version }}
