name: Core Tests
on: [push, pull_request]
permissions:
  contents: read

jobs:
  tests:
    name: Core Tests
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12-dev', pypy-3.7, pypy-3.8, pypy-3.9, pypy-3.10]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pytest
      run: pip install pytest -r requirements.txt
    - name: Run tests
      continue-on-error: False
      run: |
        python3 -m yt_dlp -v || true  # Print debug head
        python3 -Werror -m pytest -m "not download"
