name: Quick Test
on: [push, pull_request]
jobs:
  tests:
    name: Core Test
    if: "!contains(github.event.head_commit.message, 'ci skip all')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install test requirements
      run: pip install pytest pycryptodomex
    - name: Run tests
      run: ./devscripts/run_tests.sh core
  flake8:
    name: Linter
    if: "!contains(github.event.head_commit.message, 'ci skip all')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install flake8
      run: pip install flake8
    - name: Make lazy extractors
      run: python devscripts/make_lazy_extractors.py
    - name: Run flake8
      run: flake8 .
  precommit:
    name: Pre-commit CI
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip all')"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Run pre-commit
      uses: pre-commit/action@v2.0.3
      with:
        extra_args:
