name: Release (nightly)
on:
  push:
    branches:
      - master
    paths:
      - "yt_dlp/**.py"
      - "!yt_dlp/version.py"
concurrency:
  group: release-nightly
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  release:
    if: vars.BUILD_NIGHTLY != ''
    uses: ./.github/workflows/release.yml
    with:
      prerelease: true
      source: nightly
    permissions:
      contents: write
      packages: write
    secrets: inherit
